//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataRecords
    {
        public int id { get; set; }
        public string Code { get; set; }
        public string Type { get; set; }
        public string Rate { get; set; }
        public string Hours { get; set; }
        public string Total { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
